name: "🐞 Bug Report (C++)"
description: "Report a reproducible problem with environment details."
title: "[Bug]: "
labels: [bug, triage]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide a **minimal reproducible example** (MRE) and environment details so we can quickly reproduce and fix it.

  - type: input
    id: summary
    attributes:
      label: "Summary"
      placeholder: "Crash when parsing UTF-8 header on Windows"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Clear, minimal steps. Include input files or a gist link if needed."
      placeholder: |
        1. Configure with CMake flags ...
        2. Build in Release
        3. Run: ./app --flag
        4. Observe crash
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      placeholder: "Program should parse header and return 0"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      placeholder: "Segmentation fault at parser.cpp:123"
    validations:
      required: true

  - type: textarea
    id: mre
    attributes:
      label: "Minimal Reproducer (code + CMake)"
      description: "Paste a minimal snippet + CMakeLists.txt fragment (or link to a small repo)."
      placeholder: |
        // main.cpp
        int main() { /* ... */ }

        # CMakeLists.txt
        cmake_minimum_required(VERSION 3.20)
        project(mre LANGUAGES CXX)
        set(CMAKE_CXX_STANDARD 20)
        add_executable(mre main.cpp)
      render: cpp
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: "Project Version / Commit"
      placeholder: "v1.4.2 or commit abc1234"
    validations:
      required: true

  - type: dropdown
    id: buildsystem
    attributes:
      label: "Build System"
      options:
        - CMake
        - Meson
        - Bazel
        - QMake
        - Other
    validations:
      required: true

  - type: input
    id: cmake_version
    attributes:
      label: "CMake Version (if applicable)"
      placeholder: "3.28.3"
    validations:
      required: false

  - type: dropdown
    id: compiler
    attributes:
      label: "Compiler"
      options:
        - GCC
        - Clang/LLVM
        - MSVC
        - AppleClang
        - ICC/ICX
        - Other
    validations:
      required: true

  - type: input
    id: compiler_version
    attributes:
      label: "Compiler Version"
      placeholder: "GCC 13.2 / Clang 17.0.6 / MSVC 19.41"
    validations:
      required: true

  - type: dropdown
    id: cpp_std
    attributes:
      label: "C++ Standard"
      options:
        - C++11
        - C++14
        - C++17
        - C++20
        - C++23
        - GNU++ (e.g., gnu++20)
    validations:
      required: true

  - type: checkboxes
    id: build_type
    attributes:
      label: "Build Type"
      options:
        - label: "Debug"
        - label: "Release"
        - label: "RelWithDebInfo"
        - label: "MinSizeRel"

  - type: input
    id: os
    attributes:
      label: "OS / Distro / Version"
      placeholder: "Windows 11 23H2 / Ubuntu 22.04 / macOS 14.3"
    validations:
      required: true

  - type: input
    id: arch
    attributes:
      label: "Architecture"
      placeholder: "x86_64 / arm64 / other"
    validations:
      required: true

  - type: input
    id: toolchain
    attributes:
      label: "Toolchain File or Preset (if any)"
      placeholder: "cmake --preset clang-libc++ / vcpkg.cmake / conan profile"
    validations:
      required: false

  - type: checkboxes
    id: sanitizers
    attributes:
      label: "Sanitizers / Tools"
      options:
        - label: "ASan"
        - label: "UBSan"
        - label: "TSan"
        - label: "MSan"
        - label: "Valgrind"
        - label: "Addressable repro not possible"
    validations:
      required: false

  - type: textarea
    id: backtrace
    attributes:
      label: "Backtrace / Crash Logs"
      description: "From gdb/lldb/WinDbg; redact secrets."
      render: text
      placeholder: |
        (gdb) bt
        #0 ...
    validations:
      required: false

  - type: textarea
    id: dep_versions
    attributes:
      label: "Dependencies & Versions"
      description: "List relevant third-party libs (vcpkg/Conan/system packages)."
      placeholder: |
        fmt 10.2.1, spdlog 1.13.0, Boost 1.83, OpenSSL 3.2
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I searched existing issues"
          required: true
        - label: "I can reproduce with latest main/nightly"
          required: true
        - label: "I provided a minimal repro or clear steps"
          required: true
