name: "🗣️ General Report"
description: "General feedback, QOL improvements, or questions."
title: "[General]: "
labels: [general]
assignees: []
body:
  - type: textarea
    id: context
    attributes:
      label: "Context / Feedback"
      placeholder: "Share your thoughts or questions."
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I searched existing issues and discussions"
          required: true
